/**
 * App Constants
 */
export const USER_STATE_NOT_LOGGED_IN = 'app/USER_STATE/NOT_LOGGED_IN';
export const USER_STATE_LOGGING_IN = 'app/USER_STATE/LOGGING_IN';
export const USER_STATE_LOGIN_SUCCESS = 'app/USER_STATE/LOGIN_SUCCESS';
export const USER_STATE_LOGIN_FAILURE = 'app/USER_STATE/LOGIN_FAILURE';
